name: RELEASE
on:
    schedule:
        - cron: '0 2 * * SUN'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - run: npm ci
            - name: Release 
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
